### ISSUE TITLE
🐞 - `taiga-family/ci/actions/setup/checkout` fails job after merge

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/ci#66]
### Description

<img height="300" src="https://github.com/taiga-family/taiga-ui/assets/35179038/763acc9d-5640-4e58-8138-fe21bb1f2556">

Example:
https://github.com/taiga-family/taiga-ui/actions/runs/7198638030/job/19608550014
<img width="1764" alt="Screenshot 2023-12-15 at 12 16 01" src="https://github.com/taiga-family/taiga-ui/assets/35179038/3b8066ee-8278-459a-adf9-321c4eade6cb">

____

If we replace `taiga-family/ci/actions/setup/checkout` with simple `actions/checkout` => no error
* https://github.com/taiga-family/ng-web-apis/pull/355/files

**Comment by splincode** [comment]
checkout action was removed
